# Generated by Django 3.0.4 on 2020-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('content_path', models.FileField(upload_to='static/blogs/articles')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
